### ISSUE TITLE
Breaks ThaumicBoots in dev

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/CodeChickenCore#45]
### Your GTNH Discord Username

DarkShadow44

### Mod Version

1.4.12

### Bug Report

When using https://github.com/GTNewHorizons/ThaumicBoots, adding the dependency `api("com.github.GTNewHorizons:CodeChickenCore:1.4.12:dev")` and running `gradlew runClient21
` the run fails.

This is a regression, bisected to https://github.com/GTNewHorizons/CodeChickenCore/pull/36/changes/fd159c8bb9b8c6208c016fc2cd05c94877797fa2

```
Caused by: java.lang.NoSuchMethodError: 'int net.minecraft.util.MathHelper.func_76125_a(int, int, int)'
        at Launch//com.emoniph.witchery.util.Config.sync(Config.java:325)
        at Launch//com.emoniph.witchery.util.Config.init(Config.java:198)
        at Launch//com.emoniph.witchery.Witchery.preInit(Witchery.java:122)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at Launch//cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at System//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at System//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at System//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at System//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at System//com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at Launch//cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at Launch//cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at System//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at System//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at System//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at System//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at System//com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at Launch//cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at Launch//cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
        ... 16 more
```

### Java Version

Java 21

### Mod List or GTNH Pack Version

ThaumicBoots repo with this mod added

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

**Comment by DarkShadow44** [comment]
@Alexdoru Since you made the code, would you mind taking a look? ASM is being very weird here
